server:
  port: 6004
  tomcat:
    max-thread: 4
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/accsprofile
    username: accs
    password: accs
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
  session:
    store-type: redis
  #redis配置
  redis:
    host: redis
    port: 6379
    timeout: 1800
  rabbitmq:
    host: rabbit
    port: 5672
    username: admin
    password: admin
    virtual-host: /accs
management:
  security.enabled: false
logging:
  path: log/
security:
  sessions: never
  basic:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false
eureka:
  client:
    enabled: true