spring:
  datasource:
    url: jdbc:mysql://47.100.183.250:3306/wuxi
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#   url: jdbc:mysql://172.40.0.65:3308/accssit
#   username: accs
#   password: accs
#   driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 47.100.183.250
    port: 5672
    username: guest
    password: guest
    virtual-host: /dev
  zipkin:
    enabled: false
  session:
    store-type: hash-map
  redis:
    host: 47.100.183.250
    port: 6379
    timeout: 18000
    
server:
  port: 6001
  
security:
  basic:
    enabled: false
#统一会员账户信息
wxsmk:
  summary-account: 15000093071753
  uid: Z32081
  mrchCode: 3450
  guarantSubAcct: 3450000000000005
  tranWebName: 惠民优选
  configpath: D:\\wuxi\\accs\\accs-boot\\src\\main\\resources\\config.properties
logging:
  config: classpath:logback.xml
pay:
  reqUrl: https://citycard-stg.pingan.com.cn
  partnerId: bbd0762a34f045f28e150e9b3f71cbeb
  key: 30ca0fd6c3d6415faaab27cd1d9799cc
