eureka:
  client:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://47.100.183.250:3306/wuxi_mers
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 47.100.183.250
    username: guest
    password: guest
    virtual-host: /accs
  zipkin:
    enabled: false
  session:
    store-type: hash-map
  redis:
    host: 47.100.183.250
    port: 6379
    timeout: 18000
      
security:
  basic:
    enabled: false

hystrix:
 command:
    default:
      execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000    

feign:
  hystrix:
    enabled: true              
