server:
  port: 6004
  tomcat:
    max-thread: 4
spring:
  datasource:
    url: jdbc:mysql://47.100.183.250:3306/profile
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
  session:
    store-type: redis
  #redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 1800
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /dev
management:
  security.enabled: false
logging:
  path: log/
security:
  sessions: never
  basic:
    enabled: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false
eureka:
  client:
    enabled: true
