spring:
  datasource:
    url: jdbc:mysql://mysql:3306/collect
    username: collect
    password: collect
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
  session:
    store-type: redis
  #redis配置
  redis:
    host: redis
    port: 6379
    timeout: 180
  rabbitmq:
    host: rabbit
    port: 5672
    username: admin
    password: admin
    virtual-host: /dev
management:
  security.enabled: false
logging:
  path: log/
security:
  sessions: never
  basic:
    enabled: false
server:
  tomcat:
    max-thread: 4
endpoints:
  shutdown:
    enabled: true
    sensitive: false

eureka:
  client:
    enabled: true
